name: pip-testing

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
        python-version: ['3.9.13', '3.10.11', '3.11.8', '3.12.8', '3.13.2']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: gowridurgad/setup-python@pipversion
      with:
        python-version: '${{ matrix.python-version }}'
        pip-version: '23'

    - name: Check pip version
      run: pip --version
  
