
name: pip-testing

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest, macos-13, ubuntu-24.04-arm, windows-11-arm]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.13t']
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: gowridurgad/setup-python@pipversion
      with:
        python-version: '${{ matrix.python-version }}'
        pip-version: '23'
        
    - name: Check pip version
      run: pip --version
